# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rainbondVersion: v5.2.1-cloud

## Install Default RBAC roles and bindings
rbac:
  create: true
  apiVersion: v1

## Service account name and whether to create it
serviceAccount:
  create: true
  name:

# rainbondOperator
rainbondOperator:
  name: rainbond-operator
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond-operator
    tag: v1.0.1-cloud
    pullPolicy: IfNotPresent
  regionDBName: region
  logLevel: 4

# openapi
openapi:
  name: openapi
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-op-ui
    tag: v1.0.1-cloud 
    pullPolicy: IfNotPresent
  port: 8080
  nodePort: 30008
  installMode: WithoutPackage
  onlyRegion: false
  sentinelImage: registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond-operator-sentinel

rainbond:
  imageRepository: registry.cn-hangzhou.aliyuncs.com/goodrain
