go_import_path: github.com/goodrain/rainbond-operator

# use the latest ubuntu environment (18.04) available on travis
dist: bionic

language: go
# You don't need to test on very old versions of the Go compiler. It's the user's
# responsibility to keep their compiler up to date.
go:
  - 1.13.x

env: GO111MODULE=off

services:
  - docker

git:
  depth: 1

jobs:
  include:
    - stage: test
      script: make test
    - stage: build
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make build; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then make push; fi'
