sudo: required

services:
  - docker

git:
  depth: 1

script:
  - make test
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make build; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then make push; fi'
