sudo: required

services:
  - docker

git:
  depth: 1

jobs:
  include:
    - stage: test
      script: make test
    - stage: build
      script: 
      - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make build; fi'
      - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then make push; fi'
  
