apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: rbd-system
  name: grdata
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: rbd-nfs
