apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: privateregistries.privateregistry.rainbond.io
spec:
  group: privateregistry.rainbond.io
  names:
    kind: PrivateRegistry
    listKind: PrivateRegistryList
    plural: privateregistries
    singular: privateregistry
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: PrivateRegistry is the Schema for the privateregistries API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PrivateRegistrySpec defines the desired state of PrivateRegistry
          properties:
            custom_private_registry:
              type: string
          type: object
        status:
          description: PrivateRegistryStatus defines the observed state of PrivateRegistry
          properties:
            phase:
              description: Phase is the provisoner running phase
              type: string
          required:
          - phase
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
