apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rbdcomponents.rainbond.io
spec:
  group: rainbond.io
  names:
    kind: RbdComponent
    listKind: RbdComponentList
    plural: rbdcomponents
    singular: rbdcomponent
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: RbdComponent is the Schema for the rbdcomponents API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RbdComponentSpec defines the desired state of RbdComponent
          properties:
            logLevel:
              description: LogLevel -
              type: string
            type:
              description: type of rainbond component
              type: string
            version:
              description: version of rainbond component
              type: string
          required:
          - type
          - version
          type: object
        status:
          description: RbdComponentStatus defines the observed state of RbdComponent
          properties:
            message:
              type: string
            phase:
              description: RbdComponentPhase is the phase of rainbond component
              type: string
            podStatus:
              description: PodStatus -
              properties:
                healthy:
                  description: Healthy are the component pods that pass the liveness.
                  items:
                    type: string
                  type: array
                ready:
                  description: Ready are the component pods that are ready to serve
                    requests The pod names are the same as the component pod names
                  items:
                    type: string
                  type: array
                unHealthy:
                  description: Healthy are the component pods that pass the de liveness.
                  items:
                    type: string
                  type: array
                unready:
                  description: Unready are the components not ready to serve requests
                  items:
                    type: string
                  type: array
              type: object
          required:
          - message
          - podStatus
          type: object
      required:
      - spec
      - status
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
