apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: globalconfigs.rainbond.io
spec:
  group: rainbond.io
  names:
    kind: GlobalConfig
    listKind: GlobalConfigList
    plural: globalconfigs
    singular: globalconfig
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: GlobalConfig is the Schema for the globalconfigs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GlobalConfigSpec defines the desired state of GlobalConfig
          properties:
            dbInfo:
              description: the db connection information that rainbond component will
                be used. rainbond-operator will create one if DBInfo is empty
              properties:
                host:
                  type: string
                password:
                  type: string
                port:
                  type: integer
                username:
                  type: string
              required:
              - host
              - password
              - port
              - username
              type: object
            etcdInfo:
              description: the etcd connection information that rainbond component
                will be used. rainbond-operator will create one if EtcdInfo is empty
              properties:
                endpoints:
                  items:
                    type: string
                  type: array
              required:
              - endpoints
              type: object
            imageRepositry:
              description: default goodrain.me
              type: string
            storageClassName:
              description: the storage class that rainbond component will be used.
                rainbond-operator will create one if StorageClassName is empty
              type: string
          type: object
        status:
          description: GlobalConfigStatus defines the observed state of GlobalConfig
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
