apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rainbonds.rainbond.GLYASAI.com
spec:
  group: rainbond.GLYASAI.com
  names:
    kind: Rainbond
    listKind: RainbondList
    plural: rainbonds
    singular: rainbond
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Rainbond is the Schema for the rainbonds API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RainbondSpec defines the desired state of Rainbond
          properties:
            versoin:
              description: Rainbond's version
              type: string
          type: object
        status:
          description: RainbondStatus defines the observed state of Rainbond
          properties:
            phase:
              description: Phase is the rainbond running phase
              type: string
          required:
          - phase
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
