apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: globalconfigs.rainbond.io
spec:
  group: rainbond.io
  names:
    kind: GlobalConfig
    listKind: GlobalConfigList
    plural: globalconfigs
    singular: globalconfig
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: GlobalConfig is the Schema for the globalconfigs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GlobalConfigSpec defines the desired state of GlobalConfig
          properties:
            availPorts:
              items:
                properties:
                  nodeIP:
                    type: string
                  nodeName:
                    type: string
                  port:
                    type: integer
                type: object
              type: array
            etcdConfig:
              description: the etcd connection information that rainbond component
                will be used. rainbond-operator will create one if EtcdConfig is empty
              properties:
                endpoints:
                  description: Endpoints is a list of URLs.
                  items:
                    type: string
                  type: array
                selector:
                  description: Secret to mount to read certificate files for tls.
                  properties:
                    matchExpressions:
                      description: matchExpressions is a list of label selector requirements.
                        The requirements are ANDed.
                      items:
                        description: A label selector requirement is a selector that
                          contains values, a key, and an operator that relates the
                          key and values.
                        properties:
                          key:
                            description: key is the label key that the selector applies
                              to.
                            type: string
                          operator:
                            description: operator represents a key's relationship
                              to a set of values. Valid operators are In, NotIn, Exists
                              and DoesNotExist.
                            type: string
                          values:
                            description: values is an array of string values. If the
                              operator is In or NotIn, the values array must be non-empty.
                              If the operator is Exists or DoesNotExist, the values
                              array must be empty. This array is replaced during a
                              strategic merge patch.
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                    matchLabels:
                      additionalProperties:
                        type: string
                      description: matchLabels is a map of {key,value} pairs. A single
                        {key,value} in the matchLabels map is equivalent to an element
                        of matchExpressions, whose key field is "key", the operator
                        is "In", and the values array contains only "value". The requirements
                        are ANDed.
                      type: object
                  type: object
                useTLS:
                  description: Whether to use tls to connect to etcd
                  type: boolean
              required:
              - endpoints
              - selector
              - useTLS
              type: object
            imageHub:
              description: default goodrain.me
              properties:
                domain:
                  type: string
                password:
                  type: string
                username:
                  type: string
              type: object
            kubeAPIHost:
              description: KubeAPIHost must be a host string, a host:port pair, or
                a URL to the base of the apiserver. If a URL is given then the (optional)
                Path of that URL represents a prefix that must be appended to all
                request URIs used to access the apiserver. This allows a frontend
                proxy to easily relocate all of the apiserver endpoints.
              type: string
            regionDatabase:
              description: the region database information that rainbond component
                will be used. rainbond-operator will create one if DBInfo is empty
              properties:
                host:
                  type: string
                password:
                  type: string
                port:
                  type: integer
                username:
                  type: string
              required:
              - host
              - password
              - port
              - username
              type: object
            storageClassName:
              description: the storage class that rainbond component will be used.
                rainbond-operator will create one if StorageClassName is empty
              type: string
            uiDatabase:
              description: the ui database information that rainbond component will
                be used. rainbond-operator will create one if DBInfo is empty
              properties:
                host:
                  type: string
                password:
                  type: string
                port:
                  type: integer
                username:
                  type: string
              required:
              - host
              - password
              - port
              - username
              type: object
          type: object
        status:
          description: GlobalConfigStatus defines the observed state of GlobalConfig
          properties:
            phase:
              description: Rainbond cluster installation phase
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
