apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rainbondclusters.rainbond.io
spec:
  group: rainbond.io
  names:
    kind: RainbondCluster
    listKind: RainbondClusterList
    plural: rainbondclusters
    singular: rainbondcluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: RainbondCluster is the Schema for the rainbondclusters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RainbondClusterSpec defines the desired state of RainbondCluster
          properties:
            etcdConfig:
              description: the etcd connection information that rainbond component
                will be used. rainbond-operator will create one if EtcdConfig is empty
              properties:
                endpoints:
                  description: Endpoints is a list of URLs.
                  items:
                    type: string
                  type: array
                selector:
                  description: Secret to mount to read certificate files for tls.
                  properties:
                    matchExpressions:
                      description: matchExpressions is a list of label selector requirements.
                        The requirements are ANDed.
                      items:
                        description: A label selector requirement is a selector that
                          contains values, a key, and an operator that relates the
                          key and values.
                        properties:
                          key:
                            description: key is the label key that the selector applies
                              to.
                            type: string
                          operator:
                            description: operator represents a key's relationship
                              to a set of values. Valid operators are In, NotIn, Exists
                              and DoesNotExist.
                            type: string
                          values:
                            description: values is an array of string values. If the
                              operator is In or NotIn, the values array must be non-empty.
                              If the operator is Exists or DoesNotExist, the values
                              array must be empty. This array is replaced during a
                              strategic merge patch.
                            items:
                              type: string
                            type: array
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                    matchLabels:
                      additionalProperties:
                        type: string
                      description: matchLabels is a map of {key,value} pairs. A single
                        {key,value} in the matchLabels map is equivalent to an element
                        of matchExpressions, whose key field is "key", the operator
                        is "In", and the values array contains only "value". The requirements
                        are ANDed.
                      type: object
                  type: object
                useTLS:
                  description: Whether to use tls to connect to etcd
                  type: boolean
              type: object
            imageHub:
              properties:
                domain:
                  type: string
                namespace:
                  type: string
                password:
                  type: string
                username:
                  type: string
              type: object
            rainbondImageRepositoryHost:
              description: Domain name of the image repository which Rainbond is installed
                Default goodrain.me
              type: string
            regionDatabase:
              description: the region database information that rainbond component
                will be used. rainbond-operator will create one if DBInfo is empty
              properties:
                host:
                  type: string
                password:
                  type: string
                port:
                  type: integer
                username:
                  type: string
              type: object
            storageClassName:
              description: the storage class that rainbond component will be used.
                rainbond-operator will create one if StorageClassName is empty
              type: string
            uiDatabase:
              description: the ui database information that rainbond component will
                be used. rainbond-operator will create one if DBInfo is empty
              properties:
                host:
                  type: string
                password:
                  type: string
                port:
                  type: integer
                username:
                  type: string
              type: object
          type: object
        status:
          description: RainbondClusterStatus defines the observed state of RainbondCluster
          properties:
            NodeAvailPorts:
            gatewayIngressIPs:
              description: Ingress IP addresses of rbd-gateway. If not specified,
                the IP of the node where the rbd-gateway is located will be used.
              items:
                type: string
              type: array
            gatewayNodes:
              description: Information about the node where the gateway is located.
                If not specified, the gateway will run on nodes where all ports do
                not conflict.
              items:
                properties:
                  nodeIP:
                    type: string
                  nodeName:
                    type: string
                  ports:
                    items:
                      type: integer
                    type: array
                type: object
              type: array
            imageHub:
              properties:
                domain:
                  type: string
                namespace:
                  type: string
                password:
                  type: string
                username:
                  type: string
              type: object
            installMode:
              description: InstallMode is the mode of Rainbond cluster installation.
              type: string
            rainbondImageRepositoryHost:
              description: Domain name of the image repository which Rainbond is installed
                Default goodrain.me
              type: string
            regionDatabase:
              description: the region database information that rainbond component
                will be used. rainbond-operator will create one if DBInfo is empty
              properties:
                host:
                  type: string
                password:
                  type: string
                port:
                  type: integer
                username:
                  type: string
              type: object
            storageClassName:
              description: the storage class that rainbond component will be used.
                rainbond-operator will create one if StorageClassName is empty
              type: string
            suffixHTTPHost:
              description: Suffix of component default domain name
              type: string
            uiDatabase:
              description: the ui database information that rainbond component will
                be used. rainbond-operator will create one if DBInfo is empty
              properties:
                host:
                  type: string
                password:
                  type: string
                port:
                  type: integer
                username:
                  type: string
              type: object
          type: object
        status:
          description: RainbondClusterStatus defines the observed state of RainbondCluster
          properties:
            NodeAvailPorts:
              items:
                properties:
                  nodeIP:
                    type: string
                  nodeName:
                    type: string
                  ports:
                    items:
                      type: integer
                    type: array
                type: object
              type: array
            conditions:
              items:
                description: RainbondClusterCondition contains details for the current
                  condition of this rainbondcluster.
                properties:
                  lastProbeTime:
                    description: Last time we probed the condition.
                    format: date-time
                    type: string
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  message:
                    description: Human-readable message indicating details about last
                      transition.
                    type: string
                  reason:
                    description: Unique, one-word, CamelCase reason for the condition's
                      last transition.
                    type: string
                  status:
                    description: Status is the status of the condition.
                    type: string
                  type:
                    description: Type is the type of the condition.
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            message:
              description: A human readable message indicating details about why the
                pod is in this condition.
              type: string
            phase:
              description: Rainbond cluster phase
              type: string
            pkgDestPath:
              description: Destination path of the installation package extraction.
              type: string
            reason:
              description: A brief CamelCase message indicating details about why
                the pod is in this state.
              type: string
            storageClasses:
              description: List of existing StorageClasses in the cluster
              items:
                properties:
                  name:
                    type: string
                  provisioner:
                    type: string
                required:
                - name
                - provisioner
                type: object
              type: array
          required:
          - pkgDestPath
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
