apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rainbondpackages.rainbond.io
spec:
  group: rainbond.io
  names:
    kind: RainbondPackage
    listKind: RainbondPackageList
    plural: rainbondpackages
    singular: rainbondpackage
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: RainbondPackage is the Schema for the rainbondpackages API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RainbondPackageSpec defines the desired state of RainbondPackage
          properties:
            pkgPath:
              description: The path where the rainbond package is located.
              type: string
          required:
          - pkgPath
          type: object
        status:
          description: RainbondPackageStatus defines the observed state of RainbondPackage
          properties:
            message:
              description: A human readable message indicating details about why the
                pod is in this condition.
              type: string
            phase:
              description: The phase of a RainbondPackage is a simple, high-level
                summary of where the Pod is in its lifecycle. The conditions array,
                the reason and message fields, and the individual container status
                arrays contain more detail about the pod's status.
              type: string
            reason:
              description: A brief CamelCase message indicating details about why
                the pod is in this state.
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
