apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storageprovisoners.storageprovisoner.rainbond.io
spec:
  group: storageprovisoner.rainbond.io
  names:
    kind: StorageProvisoner
    listKind: StorageProvisonerList
    plural: storageprovisoners
    singular: storageprovisoner
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: StorageProvisoner is the Schema for the storageprovisoners API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: StorageProvisonerSpec defines the desired state of StorageProvisoner
          properties:
            custom_provisioner:
              type: string
          type: object
        status:
          description: StorageProvisonerStatus defines the observed state of StorageProvisoner
          properties:
            phase:
              description: Phase is the provisoner running phase
              type: string
          required:
          - phase
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
