# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Install Default RBAC roles and bindings
rbac:
  create: true
  apiVersion: v1

## Service account name and whether to create it
serviceAccount:
  create: true
  name:

# rainbondOperator
rainbondOperator:
  name: rainbond-operator
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/abewang/rainbond-operator
    tag: v0.0.1
    pullPolicy: IfNotPresent

# openapi
openapi:
  name: openapi
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/abewang/rbd-op-ui
    tag: v0.0.1
    pullPolicy: IfNotPresent
  port: 8080
  nodePort: 30008
  downloadURL: https://rainbond-pkg.oss-cn-shanghai.aliyuncs.com/offline/5.1/rainbond.images.2020-02-05-5.2-dev.tgz
  downloadMD5: 45a1aeac1bb14b21e9d6dca2c76dc58df6289a4252a16dc2c0a766a422f33137
