apiVersion: apps/v1
kind: Deployment
metadata:
  name: rainbond-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rainbond-operator
  template:
    metadata:
      labels:
        name: rainbond-operator
    spec:
      serviceAccountName: rainbond-operator
      containers:
        - name: rainbond-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - rainbond-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "rainbond-operator"
