apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rainbond-operator
  namespace: rbd-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rainbond-operator
  serviceName: rainbond-operator
  template:
    metadata:
      labels:
        name: rainbond-operator
    spec:
      serviceAccountName: rainbond-operator
      containers:
        - name: operator
          image: registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond-operator:v0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OPERATOR_NAME
              value: "rainbond-operator"
          volumeMounts:
            - mountPath: /opt/rainbond/pkg
              name: rbd-pkg
            - mountPath: /var/run
              name: dockersock
        - name: openapi
          image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-op-ui:v0.0.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /opt/rainbond/pkg
              name: rbd-pkg      
      volumes:
        - name: rbd-pkg
          hostPath:
            path: /opt/rainbond/pkg
            type: DirectoryOrCreate
        - name: dockersock
          hostPath:
            path: /var/run
            type: Directory