kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rainbond-operator
  namespace: rbd-system
subjects:
- kind: ServiceAccount
  name: rainbond-operator
roleRef:
  kind: Role
  name: rainbond-operator
  apiGroup: rbac.authorization.k8s.io
