apiVersion: rainbond.io/v1alpha1
kind: RainbondCluster
metadata:
  name: rainbondcluster
  namespace: rbd-system
spec:
  installPackageConfig:
    url: https://rainbond-pkg.oss-cn-shanghai.aliyuncs.com/offline/5.2/rainbond.images.2020-02-07-5.2-dev.tgz
    md5: f8989cabef3cff564d63a9ee445c24e26ff44af96a647b3f4c980e0e780b8032
  configCompleted: true
  imageHub:
    domain: goodrain.me
  installMode: WithPackage
  installVersion: V5.2-dev


