apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: rbd-monitor
  namespace: rbd-system
spec:
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-monitor:master-dev
  priorityComponent: true
