apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: rbd-app-ui
  namespace: rbd-system
spec:
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-app-ui:V5.2-dev
  priorityComponent: true
