apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: rbd-node
  namespace: rbd-system
spec:
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-node:master-dev
  priorityComponent: true
