apiVersion: rainbond.io/v1alpha1
kind: RbdComponent
metadata:
  name: rbd-api
  namespace: rbd-system
spec:
  image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-api:master-dev
  priorityComponent: true