apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rbdcomponents.rainbond.io
spec:
  group: rainbond.io
  names:
    kind: RbdComponent
    listKind: RbdComponentList
    plural: rbdcomponents
    singular: rbdcomponent
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: RbdComponent is the Schema for the rbdcomponents API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RbdComponentSpec defines the desired state of RbdComponent
          properties:
            configs:
              additionalProperties:
                type: string
              description: component config map
              type: object
            image:
              description: Docker image name.
              type: string
            imagePullPolicy:
              description: Image pull policy. One of Always, Never, IfNotPresent.
                Defaults to Always if :latest tag is specified, or IfNotPresent otherwise.
                Cannot be updated.
              type: string
            isInitComponent:
              description: ' Whether this component needs to be created first'
              type: boolean
            logLevel:
              description: LogLevel -
              type: string
            packagePath:
              type: string
            replicas:
              description: Number of desired pods. This is a pointer to distinguish
                between explicit zero and not specified. Defaults to 1.
              format: int32
              type: integer
            type:
              description: type of rainbond component
              type: string
            version:
              description: version of rainbond component
              type: string
          required:
          - isInitComponent
          type: object
        status:
          description: RbdComponentStatus defines the observed state of RbdComponent
          properties:
            controllerName:
              description: ControllerName represents the Controller associated with
                RbdComponent The controller could be Deployment, StatefulSet or DaemonSet
              type: string
            controllerType:
              description: Type of Controller owned by RbdComponent
              type: string
            message:
              type: string
            reason:
              type: string
          required:
          - controllerName
          - controllerType
          - message
          - reason
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
